FROM node:20-alpine 

WORKDIR /usr/src/app

COPY frontend/CryptWatchFE/package.json .

RUN npm i

COPY frontend/CryptWatchFE .

RUN npm run build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]