services:
  db:
    image: postgres:13
    ports:
      - "5434:5434"
    expose:
      - "5434"
    volumes:
      - ./db:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data

    env_file:
      - stack.env
  go-be:
    build:
      context: .
      dockerfile: Dockerfile.be
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    env_file:
      - stack.env
    depends_on:
      - db

  vite-fe:
    build:
      context: .
      dockerfile: Dockerfile.fe
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_ADDRESS=http://localhost:8080
  
volumes:
  pgdata: